# Generated by Django 2.1.4 on 2018-12-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181219_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_list',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
