# Generated by Django 2.1.4 on 2018-12-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_contact_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='tag',
        ),
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tag'),
        ),
    ]
