# Generated by Django 2.1.4 on 2019-01-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_customer_latest_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_sms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_first', to='core.SMS'),
        ),
        migrations.AddField(
            model_name='customer',
            name='responded',
            field=models.BooleanField(default=False),
        )
    ]
